---
swagger: "2.0"
info:
  version: "0.1"
  title: "SpotScore API"
paths:
  /objects:
    get:
      description: "Gets `object` objects.\nMust have param **location** to return\
        \ any objects and can have optional **categories** for more specific objects.\
        \ Location can be automatic input or user input as address.\nOptional query\
        \ param of **bbox** determines the objects maximum distance from the current\
        \ **location**.\n\nLimitations: \n* Returned objects array can't be too big.\n\
        * Bbox and radius can't be too big.\n  \n"
      parameters:
      - name: "location"
        in: "query"
        description: "location of interest"
        required: true
        type: "string"
      - name: "address"
        in: "query"
        description: "address for location of interest"
        required: false
        type: "string"
      - name: "bbox"
        in: "query"
        description: "bindingbox for points of interest"
        required: false
        type: "number"
        format: "double"
      - name: "radius"
        in: "query"
        description: "radius for points of interest"
        required: false
        type: "number"
        format: "double"
      responses:
        200:
          description: "Successful response"
          schema:
            title: "ArrayOfObjects"
            type: "array"
            items:
              title: "Object"
              type: "object"
              properties:
                name:
                  type: "string"
                single:
                  type: "boolean"
        500:
          description: "Failed response"
          schema:
            title: "ErrorResponse"
            type: "string"
            example: "Bad inputs"
  /categories:
    get:
      description: "Gets `categories` array.\n"
      parameters:
      - name: "category"
        in: "query"
        description: "needed categories"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            title: "ArrayOfCategories"
            type: "array"
            items:
              title: "Categories"
              type: "object"
              properties:
                name:
                  type: "string"
                single:
                  type: "boolean"
        500:
          description: "Failed response"
          schema:
            title: "ErrorResponse"
            type: "string"
            example: "Bad inputs"
  /object/id:
    get:
      description: "Gets objects `information`.\n"
      parameters:
      - name: "id"
        in: "query"
        description: "objects id"
        required: true
        type: "number"
        format: "integer"
      responses:
        200:
          description: "Successful response"
          schema:
            title: "ObjectInformation"
            type: "string"
        500:
          description: "Failed response"
          schema:
            title: "ErrorResponse"
            type: "string"
            example: "Bad inputs"
  /nearest:
    get:
      description: "Gets nearest `object` objects.\nMust have param **location** to\
        \ return any objects and can have optional **categories** for more specific\
        \ objects. Location can be automatic input or user input as address.\nOptional\
        \ query param of **bbox** determines the objects maximum distance from the\
        \ current **location**.\n\nLimitations: \n* Returned objects array can't be\
        \ too big.\n* Bbox and radius can't be too big.\n\n  \n"
      parameters:
      - name: "location"
        in: "query"
        description: "location of interest"
        required: true
        type: "string"
      - name: "address"
        in: "query"
        description: "address for location of interest"
        required: false
        type: "string"
      - name: "bbox"
        in: "query"
        description: "bindingbox for points of interest"
        required: false
        type: "number"
        format: "double"
      - name: "radius"
        in: "query"
        description: "radius for points of interest"
        required: false
        type: "number"
        format: "double"
      - name: "nearest"
        in: "query"
        description: "boolean to get only nearest object"
        required: true
        type: "boolean"
      responses:
        200:
          description: "Successful response"
          schema:
            title: "ArrayOfObjects"
            type: "array"
            items:
              title: "Object"
              type: "object"
              properties:
                name:
                  type: "string"
                single:
                  type: "boolean"
        500:
          description: "Failed response"
          schema:
            title: "ErrorResponse"
            type: "string"
            example: "Bad inputs"
